FROM node:alpine as build-frontend

ARG VERSION

COPY frontend /srv/frontend
RUN apk add --update python3 make g++ && \
    rm -rf /var/cache/apk/*
RUN cd /srv/frontend && \
    npm ci && \
    npm run build

FROM umputun/reproxy

ENV TZ=Europe/Tallinn
COPY --from=build-frontend /srv/frontend/app /web

EXPOSE 8000

CMD ["--assets.location=/web", "--listen=0.0.0.0:8000"]
